#!/bin/bash

#CreateUD

clear

#Create update files
sudo touch UpdateC
sudo  touch Upcode
sudo touch StartC
sudo touch StopC

#Write out StartC and StopC
echo "sudo supervisorctl start video_looper" > StartC
echo "sudo supervisorctl stop video_looper" > StopC

#Declare variables
var1=false
var2=false

#Determine store
echo -e 'What store is this for? \nPlease enter in the name, not the nsn.'
read name
clear

#Determine Critical Content Information
clear
echo "Please enter in the username of the server where your files are stored."
read user
echo "Enter in the public IP address of your server."
read IP
echo -e "Enter in the FULL file path to the video folder.\nDo not include the file name."
read locale
echo -e "Enter in the FULL file path to the update file folder.\nDo not include the file name."
read locale2
echo "Enter in the password for the user."
read passwd

#Write out Upcode
echo cd /home/pi/CCD/Scripts/ToRun > Upcode 
echo sudo chmod +x update >> Upcode 
echo sudo ./update >> Upcode

#Write out info into secure file.
touch CCI
echo "#This information is very sensitive. " > CCI
echo "#Do not share with those untrusted." >> CCI
echo "#Do NOT change the order of the entries or enter new entires." >> CCI
echo "#Type." >> CCI
echo  "CCS" >> CCI #5
echo -e "#\n#\n#" >> CCI
echo "#Store name." >> CCI
echo $name >> CCI #10
echo -e "#\n#\n#" >> CCI
echo "#User." >> CCI
echo $user >> CCI #15
echo -e "#\n#\n#" >> CCI
echo "#IP address of server." >> CCI
echo $IP >> CCI #20
echo -e "#\n#\n#" >> CCI
echo "#File path to video file." >> CCI
echo $locale >> CCI #25
echo -e "#\n#\n#" >> CCI
echo "#File path to update file." >> CCI
echo $locale2 >> CCI #30
echo -e "#\n#\n#" >> CCI
echo "#Password" >> CCI
echo $passwd >> CCI #35
sudo cp CCI /home/pi/CCD
