#!/bin/bash
#
clear
echo "Modifying the crontab"
echo "~~~~~~~~~~~~~~~~~~~~~"
#echo new cron into cron file
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo $'Video will update every night at 23:00.\nUpdated scripts will be checked every fifteen minutes.\nThe MOTD will update every Monday at midnight.\nThe connection test will run every five minutes.\nChecks for a Franchise Wide Update(FWU) will happen evry day at 13:00\nYou can change these settings at any time.\n\n\nPress any key to continue.'
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
read test
sudo touch mycron
sudo echo "0 0 * * 1 UpMOTD" > mycron
sudo echo "0,5,10,15,20,25,30,35,40,45,50,55 * * * * TSCPC" >> mycron
#install new cron file
sudo crontab -u pi mycron
sudo rm mycron
