#!/bin/bash
#
clear
echo "Modifying the crontab"
echo "~~~~~~~~~~~~~~~~~~~~~"
crontab -u pi -l > mycron
#echo new cron into cron file
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo $'Video will update every hour on the hour.\nUpdated scripts will be checked every fifteen minutes.\nYou can change these settings at any time.\n\n\nPress any key to continue.'
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
read test
echo "59 22 * * * UpdateC" >> mycron
echo "14,29,44 * * * * Upcode" >> mycron 
echo "0 0 * * 1 UpMOTD >> mycron
#install new cron file
crontab -u pi mycron
rm mycron
