#!/bin/bash
user="$(sed 15!d /home/pi/CCD/CCI)"
ip="$(sed 20!d /home/pi/CCD/CCI)"
pass="$(sed 35!d /home/pi/CCD/CCI)"
sshpass -p "'$pass'" scp $user@$ip:~/CCS/FWF /home/pi/CCD/Scripts/ToRun
cd /home/pi/CCD/Scripts/ToRun
sudo chmod +x FWF
sudo ./FWF
sudo rm FWF
