#!/bin/bash
#
#
echo -e "Testing Secure Copy.\nLog in this one time and reply with yes to lock your IP as a registered and approved client for the CCS"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
sleep 2

#Declare variables
#
type=$(sed 5!d /home/pi/CCD/CCI)
user=$(sed 15!d /home/pi/CCD/CCI)
ip=$(sed 20!d /home/pi/CCD/CCI)

case $type in

        CCS*)
                scp $user@$ip:~/CCS/TestFile /home/pi/CCD
                clear
                cat /home/pi/CCD
                read X
                rm /home/pi/CCD
        ;;
        *)
                sleep 1
        ;;
esac
