#!/bin/bash
#
#
#Declare variables
#
name="$(sed 10!d /home/pi/CCD/CCI)test"
user="$(sed 15!d /home/pi/CCD/CCI)"
ip="$(sed 20!d /home/pi/CCD/CCI)"
pass="$(sed 35!d /home/pi/CCD/CCI)"
#
#
echo "$(date "+%D +%T") - This was a success!" >> /home/pi/CCD/Scripts/ToRun/$name
sshpass -p "'$pass'" scp /home/pi/CCD/Scripts/ToRun/$name $user@$ip:~/CCS/Logs
#
