#!/bin/bash
#
#
#Declare variables.
#
#
name="$(sed 10!d /home/pi/CCD/CCI)UpdateLog"
user="$(sed 15!d /home/pi/CCD/CCI)"
ip="$(sed 20!d /home/pi/CCD/CCI)"
pass="$(sed 35!d /home/pi/CCD/CCI)"
#
#
#
while getopts "yn" opt
do
    case $opt in
        y)
                sudo date >> /home/pi/CCD/Scripts/$name
                sshpass -p "'$pass'" scp /home/pi/CCD/Scripts/$name $user@$ip:~/CCS/Logs/UpdateLogs
                ;;
        n)
        ;;
        esac
done
#
